services:
  ollama-matcher:
    build:
      context: .
      dockerfile: Dockerfile_ollama
    container_name: ollama-matcher
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
      - ./models:/models
    environment:
      - OLLAMA_MODELS=/models
      - MODEL_NAME=gemma3:4b
    runtime: nvidia
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 10s
      timeout: 30s
      retries: 10
    networks:
      - matcher


  candidate_matcher:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      ollama-matcher:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_API_URL=http://ollama-matcher:11434
      - OLLAMA_MODEL_NAME=gemma3:4b
    networks:
      - matcher

  cloudflared-tunnel-candidate:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel-candidate
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=INSERT_TOKEN
    restart: always
    networks:
      - matcher

volumes:
  ollama_models:

networks:
  matcher:
    driver: bridge
