services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile_ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
      - ./models:/models
    environment:
      - OLLAMA_MODELS=/models
    runtime: nvidia
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 10s
      timeout: 5s
      retries: 5

  candidate_matcher:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  ollama_models:
