services:
  ollama-matcher:
    build:
      context: .
      dockerfile: Dockerfile_ollama
    container_name: ollama-matcher
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
      - ./models:/models
    environment:
      - OLLAMA_MODELS=/models
      - MODEL_NAME=gemma3:4b
    runtime: nvidia

  candidate_matcher:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ollama-matcher
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_API_URL=http://ollama-matcher:11434
      - OLLAMA_MODEL_NAME=gemma3:4b

volumes:
  ollama_models:
