FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y curl

VOLUME ["/root/.ollama", "/models"]
RUN mkdir -p /models && chmod 777 /models

ENV OLLAMA_MODELS="/models"
ENV MODEL_NAME="gemma3:4b"

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 11434
ENTRYPOINT ["entrypoint.sh"]
